### ISSUE TITLE
UI does not work in Firefox browser

### ISSUE THREAD

**Issue by psturc** [aerogear-attic/data-sync-ui#131]
### Affected version
Firefox 52.9.0 (64-bit)

### Error
UI won't not load.
<img width="531" alt="screen shot 2018-09-11 at 17 00 18" src="https://user-images.githubusercontent.com/4881144/45368568-33247b80-b5e4-11e8-90bf-03bee3b86ba2.png">

### How to reproduce
1. Clone this repo
2. Run `docker-compose up`
3. Run `npm run server`
4. In Firefox, navigate to `localhost:8080`

**Comment by secondsun** [comment]
![screenshot from 2018-09-12 14-50-29](https://user-images.githubusercontent.com/2413816/45446581-3af32700-b69b-11e8-800b-e8d79233aec0.png)

Works on my machine...

**Comment by danielpassos** [comment]
It works for me:

Commit used: https://github.com/aerogear/data-sync-ui/commit/9df8aa5e19e316a7628458e2dc2b8b0343d02995

<img width="1440" alt="screenshot 2018-09-13 09 35 05" src="https://user-images.githubusercontent.com/13337/45488669-7f80d000-b738-11e8-8cdf-e4770c72391b.png">
<img width="648" alt="screenshot 2018-09-13 09 35 57" src="https://user-images.githubusercontent.com/13337/45488670-7f80d000-b738-11e8-85b5-b623d1872602.png">
<img width="586" alt="screenshot 2018-09-13 09 36 06" src="https://user-images.githubusercontent.com/13337/45488671-7f80d000-b738-11e8-96b7-0cc981007092.png">

**Comment by secondsun** [comment]
Did you run npm install before you ran the server?

**Comment by psturc** [comment]
I've got the service deployed on internal infrastructure and it also does not work either: https://data-sync-ui-datasync-keycloak.apb-testing.skunkhenry.com/

**Comment by psturc** [comment]
Requires to be connected to RH VPN, since it's deployed to internal infrastructure.

**Comment by danielpassos** [comment]
It works for me on https://data-sync-ui-datasync-keycloak.apb-testing.skunkhenry.com/

<img width="1440" alt="screenshot 2018-09-17 09 35 25" src="https://user-images.githubusercontent.com/13337/45623300-3ba20980-ba5d-11e8-83a9-4cbdc5c5e15d.png">
